apiVersion: argocd.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  serverAddr: argocd-server.argocd.svc:443
  insecure: true
  plainText: false
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: argocd-credentials
      key: authToken
